language: node_js
node_js:
  - "6"
script:
  - npm run test:CI
  - npm run just-build
after_success:
  # Send coverage data to coveralls.
  - npm run test:cover:CI
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  repo: rynobax/budget-hero
  on:
    branch: master